# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from veyra.v1 import runtime_pb2 as veyra_dot_v1_dot_runtime__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in veyra/v1/runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DecisionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Decide = channel.unary_unary(
                '/veyra.v1.DecisionService/Decide',
                request_serializer=veyra_dot_v1_dot_runtime__pb2.DecisionRequest.SerializeToString,
                response_deserializer=veyra_dot_v1_dot_runtime__pb2.Decision.FromString,
                _registered_method=True)


class DecisionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Decide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecisionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Decide': grpc.unary_unary_rpc_method_handler(
                    servicer.Decide,
                    request_deserializer=veyra_dot_v1_dot_runtime__pb2.DecisionRequest.FromString,
                    response_serializer=veyra_dot_v1_dot_runtime__pb2.Decision.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'veyra.v1.DecisionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('veyra.v1.DecisionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DecisionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Decide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/veyra.v1.DecisionService/Decide',
            veyra_dot_v1_dot_runtime__pb2.DecisionRequest.SerializeToString,
            veyra_dot_v1_dot_runtime__pb2.Decision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HarnessServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/veyra.v1.HarnessService/Start',
                request_serializer=veyra_dot_v1_dot_runtime__pb2.StartRequest.SerializeToString,
                response_deserializer=veyra_dot_v1_dot_runtime__pb2.StartResponse.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/veyra.v1.HarnessService/Step',
                request_serializer=veyra_dot_v1_dot_runtime__pb2.StepRequest.SerializeToString,
                response_deserializer=veyra_dot_v1_dot_runtime__pb2.StepResponse.FromString,
                _registered_method=True)
        self.Control = channel.unary_unary(
                '/veyra.v1.HarnessService/Control',
                request_serializer=veyra_dot_v1_dot_runtime__pb2.ControlRequest.SerializeToString,
                response_deserializer=veyra_dot_v1_dot_runtime__pb2.ControlResponse.FromString,
                _registered_method=True)
        self.Inspect = channel.unary_unary(
                '/veyra.v1.HarnessService/Inspect',
                request_serializer=veyra_dot_v1_dot_runtime__pb2.InspectRequest.SerializeToString,
                response_deserializer=veyra_dot_v1_dot_runtime__pb2.InspectResponse.FromString,
                _registered_method=True)
        self.ListHarnesses = channel.unary_unary(
                '/veyra.v1.HarnessService/ListHarnesses',
                request_serializer=veyra_dot_v1_dot_runtime__pb2.ListHarnessesRequest.SerializeToString,
                response_deserializer=veyra_dot_v1_dot_runtime__pb2.ListHarnessesResponse.FromString,
                _registered_method=True)


class HarnessServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Control(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Inspect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListHarnesses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HarnessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=veyra_dot_v1_dot_runtime__pb2.StartRequest.FromString,
                    response_serializer=veyra_dot_v1_dot_runtime__pb2.StartResponse.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=veyra_dot_v1_dot_runtime__pb2.StepRequest.FromString,
                    response_serializer=veyra_dot_v1_dot_runtime__pb2.StepResponse.SerializeToString,
            ),
            'Control': grpc.unary_unary_rpc_method_handler(
                    servicer.Control,
                    request_deserializer=veyra_dot_v1_dot_runtime__pb2.ControlRequest.FromString,
                    response_serializer=veyra_dot_v1_dot_runtime__pb2.ControlResponse.SerializeToString,
            ),
            'Inspect': grpc.unary_unary_rpc_method_handler(
                    servicer.Inspect,
                    request_deserializer=veyra_dot_v1_dot_runtime__pb2.InspectRequest.FromString,
                    response_serializer=veyra_dot_v1_dot_runtime__pb2.InspectResponse.SerializeToString,
            ),
            'ListHarnesses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListHarnesses,
                    request_deserializer=veyra_dot_v1_dot_runtime__pb2.ListHarnessesRequest.FromString,
                    response_serializer=veyra_dot_v1_dot_runtime__pb2.ListHarnessesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'veyra.v1.HarnessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('veyra.v1.HarnessService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HarnessService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/veyra.v1.HarnessService/Start',
            veyra_dot_v1_dot_runtime__pb2.StartRequest.SerializeToString,
            veyra_dot_v1_dot_runtime__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/veyra.v1.HarnessService/Step',
            veyra_dot_v1_dot_runtime__pb2.StepRequest.SerializeToString,
            veyra_dot_v1_dot_runtime__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Control(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/veyra.v1.HarnessService/Control',
            veyra_dot_v1_dot_runtime__pb2.ControlRequest.SerializeToString,
            veyra_dot_v1_dot_runtime__pb2.ControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Inspect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/veyra.v1.HarnessService/Inspect',
            veyra_dot_v1_dot_runtime__pb2.InspectRequest.SerializeToString,
            veyra_dot_v1_dot_runtime__pb2.InspectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListHarnesses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/veyra.v1.HarnessService/ListHarnesses',
            veyra_dot_v1_dot_runtime__pb2.ListHarnessesRequest.SerializeToString,
            veyra_dot_v1_dot_runtime__pb2.ListHarnessesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class KernelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Submit = channel.unary_unary(
                '/veyra.v1.KernelService/Submit',
                request_serializer=veyra_dot_v1_dot_runtime__pb2.SubmitRequest.SerializeToString,
                response_deserializer=veyra_dot_v1_dot_runtime__pb2.SubmitResponse.FromString,
                _registered_method=True)
        self.Watch = channel.unary_stream(
                '/veyra.v1.KernelService/Watch',
                request_serializer=veyra_dot_v1_dot_runtime__pb2.WatchRequest.SerializeToString,
                response_deserializer=veyra_dot_v1_dot_runtime__pb2.RunEvent.FromString,
                _registered_method=True)
        self.GetRun = channel.unary_unary(
                '/veyra.v1.KernelService/GetRun',
                request_serializer=veyra_dot_v1_dot_runtime__pb2.GetRunRequest.SerializeToString,
                response_deserializer=veyra_dot_v1_dot_runtime__pb2.RunRecord.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/veyra.v1.KernelService/Cancel',
                request_serializer=veyra_dot_v1_dot_runtime__pb2.CancelRequest.SerializeToString,
                response_deserializer=veyra_dot_v1_dot_runtime__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.ListHarnesses = channel.unary_unary(
                '/veyra.v1.KernelService/ListHarnesses',
                request_serializer=veyra_dot_v1_dot_runtime__pb2.ListHarnessesRequest.SerializeToString,
                response_deserializer=veyra_dot_v1_dot_runtime__pb2.ListHarnessesResponse.FromString,
                _registered_method=True)


class KernelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Submit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListHarnesses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KernelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Submit': grpc.unary_unary_rpc_method_handler(
                    servicer.Submit,
                    request_deserializer=veyra_dot_v1_dot_runtime__pb2.SubmitRequest.FromString,
                    response_serializer=veyra_dot_v1_dot_runtime__pb2.SubmitResponse.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=veyra_dot_v1_dot_runtime__pb2.WatchRequest.FromString,
                    response_serializer=veyra_dot_v1_dot_runtime__pb2.RunEvent.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=veyra_dot_v1_dot_runtime__pb2.GetRunRequest.FromString,
                    response_serializer=veyra_dot_v1_dot_runtime__pb2.RunRecord.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=veyra_dot_v1_dot_runtime__pb2.CancelRequest.FromString,
                    response_serializer=veyra_dot_v1_dot_runtime__pb2.CancelResponse.SerializeToString,
            ),
            'ListHarnesses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListHarnesses,
                    request_deserializer=veyra_dot_v1_dot_runtime__pb2.ListHarnessesRequest.FromString,
                    response_serializer=veyra_dot_v1_dot_runtime__pb2.ListHarnessesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'veyra.v1.KernelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('veyra.v1.KernelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KernelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Submit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/veyra.v1.KernelService/Submit',
            veyra_dot_v1_dot_runtime__pb2.SubmitRequest.SerializeToString,
            veyra_dot_v1_dot_runtime__pb2.SubmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/veyra.v1.KernelService/Watch',
            veyra_dot_v1_dot_runtime__pb2.WatchRequest.SerializeToString,
            veyra_dot_v1_dot_runtime__pb2.RunEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/veyra.v1.KernelService/GetRun',
            veyra_dot_v1_dot_runtime__pb2.GetRunRequest.SerializeToString,
            veyra_dot_v1_dot_runtime__pb2.RunRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/veyra.v1.KernelService/Cancel',
            veyra_dot_v1_dot_runtime__pb2.CancelRequest.SerializeToString,
            veyra_dot_v1_dot_runtime__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListHarnesses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/veyra.v1.KernelService/ListHarnesses',
            veyra_dot_v1_dot_runtime__pb2.ListHarnessesRequest.SerializeToString,
            veyra_dot_v1_dot_runtime__pb2.ListHarnessesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
